apiVersion: v1
kind: Service
metadata:
  labels:
    app: rss2kindle-web
  name: rss2kindle-web
  annotations:
    cloud.google.com/app-protocols: '{"https":"HTTPS"}'
spec:
  type: NodePort
  ports:
    - name: https
      port: 443
      targetPort: 8443
      nodePort: 30023
      protocol: TCP
  selector:
    app: rss2kindle-web