version: '3.3'
services:
  mongo:
    build:
      context: ./mongo
    image: rss2kindle/mongo:3.3
    container_name: rss2kindle-mongo
    ports:
      - "27017:27017"
    networks:
      rss2kindle:
        aliases:
          - mongodb
  mailhog:
    build:
      context: ./mailhog
    image: rss2kindle/mailhog:3.3
    container_name: rss2kindle-mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      rss2kindle:
        aliases:
          - mailhog
    labels:
      - "traefik.http.routers.mailhog.rule=Host(`smtp`)"
      - "traefik.http.services.mailhog.loadbalancer.server.port=8025"
  rss2kindle-api:
    build:
      context: ./tomcat
      dockerfile: rss2kindle-api-dockerfile
    image: rss2kindle/api:3.3
    container_name: rss2kindle-api
    ports:
      - "7443:8443"
    networks:
      rss2kindle:
        aliases:
          - rss2kindle-api
    environment:
      - mongodb.host=mongodb
      - smtp.host=mailhog
      - smtp.port=1025
    volumes:
      - ../logs:/usr/local/tomcat/logs:rw
      - ../data:/usr/local/tomcat/data:rw
#    labels:
#      - "traefik.enable=true"
#      - "traefik.http.routers.rss2kindle-api.rule=Host(`api`)"
#      - "traefik.http.routers.rss2kindle-api.tls=true"
#      - "traefik.http.services.rss2kindle-api.loadbalancer.server.port=7443"
  rss2kindle-web:
    build:
      context: ./tomcat
      dockerfile: rss2kindle-web-dockerfile
    image: rss2kindle/web:3.3
    container_name: rss2kindle-web
    ports:
      - "8443:8443"
    networks:
      - rss2kindle
    environment:
      - rest.host=https://rss2kindle-api
      - rest.port=7443
    volumes:
      - ../logs:/usr/local/tomcat/logs:rw
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.rss2kindle-web.rule=Host(`web`)"
      - "traefik.http.routers.rss2kindle-web.tls=true"
      - "traefik.http.services.rss2kindle-web.loadbalancer.sticky=true"
      - "traefik.http.services.rss2kindle-web.loadbalancer.server.port=8443"
  reverse-proxy:
      # The official v2.0 Traefik docker image
      image: traefik:v2.0
      container_name: rss2kindle-proxy
      # Enables the web UI and tells Traefik to listen to docker
      command:
        - "--api.insecure=true"
        - "--providers.docker=true"
        - "--providers.docker.network=rss2kindle"
      ports:
        # The HTTP port
        - "80:80"
        # The Web UI (enabled by --api.insecure=true)
        - "8080:8080"
      volumes:
        # So that Traefik can listen to the Docker events
        - /var/run/docker.sock:/var/run/docker.sock
networks:
  rss2kindle:
