version: '3.3'
services:
  mongo:
    build: 
      context: ./mongo
    image: rss2kindle/mongo:v1
    container_name: mongo_act
    ports:
      - "27017:27017"
    networks:
      rss2kindle:
        aliases:
          - mongodb
  mailhog:
    build:
      context: ./mailhog
    image: rss2kindle/mailhog:v1
    container_name: mailhog_act
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      rss2kindle:
        aliases:
          - mailhog
  tomcat:
    build: 
      context: ./tomcat
    image: rss2kindle/tomcat:v1
    container_name: tomcat_act
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - rss2kindle
    volumes:
      - ../logs:/usr/local/tomcat/logs:rw
      - ../data:/usr/local/tomcat/data:rw
networks:
  rss2kindle:
