version: '2'
services:
  mongo:
    build: 
      context: ./mongo
    container_name: mongo_act
    ports:
      - "27017:27017"
    networks:
      rss2kindle:
        aliases:
          - mongodb
  mailhog:
    build:
      context: ./mailhog
    container_name: mailhog_act
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      rss2kindle:
        aliases:
          - mailhog
  tomcat:
    build: 
      context: ./tomcat
    container_name: tomcat_act
    ports:
      - "8080:8080"
      - "8443:8443"
    networks:
      - rss2kindle
    volumes:
      - ../kindle:/usr/local/kindle
      - ../logs:/usr/local/tomcat/logs:rw
      - ../data:/usr/local/tomcat/data:rw
networks:
  rss2kindle: